import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface TransactionReceipt {
  id: string;
  type: string;
  amount: number;
  currency: string;
  description?: string;
  recipientName?: string;
  recipientAccount?: string;
  referenceNumber: string;
  status: string;
  date: string;
  accountNumber?: string;
}

interface StatementData {
  accountNumber: string;
  accountType: string;
  currency: string;
  balance: number;
  periodStart: string;
  periodEnd: string;
  transactions: TransactionReceipt[];
  userName: string;
}

interface jsPDFWithAutoTable extends jsPDF {
  lastAutoTable: {
    finalY: number;
  };
}

const formatCurrency = (amount: number, currency: string = 'USD') => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency,
  }).format(amount);
};

const addHeader = (doc: jsPDF) => {
  // Logo/Bank name
  doc.setFillColor(255, 77, 77);
  doc.rect(20, 15, 10, 10, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('N', 22.5, 23);

  doc.setTextColor(15, 15, 15);
  doc.setFontSize(18);
  doc.text('Galecloveb', 35, 23);

  // Bank details
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('Tampa, Florida', 35, 30);
  doc.text('support@galecloveb.com | +1 (808) 206-5163', 35, 35);

  // Separator line
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 42, 190, 42);
};

const addFooter = (doc: jsPDF, pageNumber: number) => {
  const pageHeight = doc.internal.pageSize.height;
  
  doc.setDrawColor(200, 200, 200);
  doc.line(20, pageHeight - 25, 190, pageHeight - 25);
  
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(
    'This is an official document generated by Galecloveb.',
    105,
    pageHeight - 18,
    { align: 'center' }
  );
  doc.text(
    `© ${new Date().getFullYear()} Galecloveb. All rights reserved.`,
    105,
    pageHeight - 13,
    { align: 'center' }
  );
  doc.text(`Page ${pageNumber}`, 190, pageHeight - 13, { align: 'right' });
};

export const generateTransactionReceipt = (transaction: TransactionReceipt) => {
  const doc = new jsPDF() as jsPDFWithAutoTable;
  
  addHeader(doc);

  // Receipt title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 15, 15);
  doc.text('Transaction Receipt', 105, 55, { align: 'center' });

  // Transaction type badge
  const typeColor = transaction.type === 'credit' ? [34, 197, 94] : [239, 68, 68];
  doc.setFillColor(typeColor[0], typeColor[1], typeColor[2]);
  doc.roundedRect(85, 60, 40, 8, 2, 2, 'F');
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text(transaction.type.toUpperCase(), 105, 66, { align: 'center' });

  // Transaction details
  const startY = 80;
  const details = [
    ['Reference Number', transaction.referenceNumber],
    ['Date', new Date(transaction.date).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })],
    ['Amount', formatCurrency(transaction.amount, transaction.currency)],
    ['Status', transaction.status.charAt(0).toUpperCase() + transaction.status.slice(1)],
    ['Description', transaction.description || 'N/A'],
  ];

  if (transaction.recipientName) {
    details.push(['Recipient Name', transaction.recipientName]);
  }
  if (transaction.recipientAccount) {
    details.push(['Recipient Account', transaction.recipientAccount]);
  }
  if (transaction.accountNumber) {
    details.push(['From Account', transaction.accountNumber]);
  }

  autoTable(doc, {
    startY,
    head: [],
    body: details,
    theme: 'plain',
    styles: {
      fontSize: 11,
      cellPadding: 6,
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 60, textColor: [100, 100, 100] },
      1: { cellWidth: 110, textColor: [15, 15, 15] },
    },
    alternateRowStyles: {
      fillColor: [248, 248, 248],
    },
  });

  // Amount highlight box
  const finalY = doc.lastAutoTable.finalY + 15;
  doc.setFillColor(255, 77, 77, 0.1);
  doc.roundedRect(20, finalY, 170, 30, 3, 3, 'F');
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text('Total Amount', 30, finalY + 12);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 77, 77);
  doc.text(formatCurrency(transaction.amount, transaction.currency), 30, finalY + 24);

  addFooter(doc, 1);

  return doc;
};

export const generateMonthlyStatement = (data: StatementData) => {
  const doc = new jsPDF() as jsPDFWithAutoTable;
  let currentPage = 1;

  addHeader(doc);

  // Statement title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 15, 15);
  doc.text('Monthly Account Statement', 105, 55, { align: 'center' });

  // Period badge
  doc.setFillColor(15, 15, 15);
  doc.roundedRect(60, 60, 90, 8, 2, 2, 'F');
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text(`${data.periodStart} - ${data.periodEnd}`, 105, 66, { align: 'center' });

  // Account summary
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 15, 15);
  doc.text('Account Summary', 20, 85);

  const accountDetails = [
    ['Account Holder', data.userName],
    ['Account Number', data.accountNumber],
    ['Account Type', data.accountType.charAt(0).toUpperCase() + data.accountType.slice(1)],
    ['Currency', data.currency],
    ['Current Balance', formatCurrency(data.balance, data.currency)],
  ];

  autoTable(doc, {
    startY: 90,
    head: [],
    body: accountDetails,
    theme: 'plain',
    styles: {
      fontSize: 10,
      cellPadding: 4,
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 50, textColor: [100, 100, 100] },
      1: { cellWidth: 80, textColor: [15, 15, 15] },
    },
  });

  // Transaction history
  const tableStartY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 15, 15);
  doc.text('Transaction History', 20, tableStartY);

  const transactionRows = data.transactions.map((tx) => [
    new Date(tx.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
    tx.description || tx.type,
    tx.referenceNumber.slice(0, 12) + '...',
    tx.type === 'credit' ? '+' + formatCurrency(tx.amount, tx.currency) : '-' + formatCurrency(tx.amount, tx.currency),
  ]);

  autoTable(doc, {
    startY: tableStartY + 5,
    head: [['Date', 'Description', 'Reference', 'Amount']],
    body: transactionRows,
    theme: 'striped',
    headStyles: {
      fillColor: [15, 15, 15],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    styles: {
      fontSize: 9,
      cellPadding: 5,
    },
    columnStyles: {
      0: { cellWidth: 30 },
      1: { cellWidth: 70 },
      2: { cellWidth: 45 },
      3: { cellWidth: 35, halign: 'right' },
    },
    didDrawPage: () => {
      addFooter(doc, currentPage);
      currentPage++;
    },
  });

  // Summary stats
  const finalY = doc.lastAutoTable.finalY + 15;
  const totalCredits = data.transactions
    .filter((tx) => tx.type === 'credit')
    .reduce((sum, tx) => sum + tx.amount, 0);
  const totalDebits = data.transactions
    .filter((tx) => tx.type === 'debit')
    .reduce((sum, tx) => sum + tx.amount, 0);

  doc.setFillColor(248, 248, 248);
  doc.roundedRect(20, finalY, 170, 35, 3, 3, 'F');

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 100, 100);
  doc.text('Period Summary', 30, finalY + 10);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Credits: ${formatCurrency(totalCredits, data.currency)}`, 30, finalY + 20);
  doc.text(`Total Debits: ${formatCurrency(totalDebits, data.currency)}`, 30, finalY + 28);
  doc.text(`Net Change: ${formatCurrency(totalCredits - totalDebits, data.currency)}`, 120, finalY + 20);
  doc.text(`Transactions: ${data.transactions.length}`, 120, finalY + 28);

  addFooter(doc, currentPage);

  return doc;
};


export const downloadPDF = (doc: jsPDF, filename: string) => {
  doc.save(filename);
};

export const exportTransactionsCSV = (transactions: TransactionReceipt[], filename: string) => {
  const headers = ['Date', 'Type', 'Description', 'Amount', 'Currency', 'Reference', 'Status'];
  const rows = transactions.map((tx) => [
    new Date(tx.date).toISOString().split('T')[0],
    tx.type,
    tx.description || '',
    tx.amount.toString(),
    tx.currency,
    tx.referenceNumber,
    tx.status,
  ]);

  const csvContent = [headers, ...rows].map((row) => row.join(',')).join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  link.click();
};
