// This file is automatically generated. Do not edit it directly.
import {createClient} from '@supabase/supabase-js';
import type {Database} from './types';

const SUPABASE_URL = "https://pzagupitbrakyjxvumul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_J2sEGfZ86WR2-Huqsut7cw_5-UDDuM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
